### ISSUE TITLE
Enhancement: limit max-width of feed images

### ISSUE THREAD

**Issue by Artfunkel** [tanriol/digest#75]
I'd like to suggest this CSS rule:

``` css
article.content img { max-width:630px; height:auto; }
```

This prevents very large images in feed items from distorting the feed view. (A pixel width isn't very elegant but I've had no luck with relative width.)

This is what currently happens when expanding an article in headline view:

![width](https://f.cloud.github.com/assets/3618066/861351/0ff33b50-f5ce-11e2-8396-ef9fc8e598dc.jpg)
